version: '3.7'

services:
    db:
        container_name: postgres
        image: postgres:15.2
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - 5433:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - tweetch-backend

volumes:
    postgres_data:

networks:
    tweetch-backend:
